### ISSUE TITLE
Master branch doesn't work in browser

### ISSUE THREAD

**Issue by VarunAgw** [berrberr/streamkeys#708]
I try to build it today and all. After I try to install it in Chrome and visit options, it fails leaving this error in chrome console

```
Error handling response: Error: The argument passed when initializing an observable array must be an array, or null, or undefined.
    at Object.a.Ha (chrome-extension://hekejdakmnkficpkmibmiiadjcldfadl/js/options.js:292:381)
    at new MusicSite (chrome-extension://hekejdakmnkficpkmibmiiadjcldfadl/js/options.js:136:21)
    at chrome-extension://hekejdakmnkficpkmibmiiadjcldfadl/js/options.js:98:18
    at Array.forEach (<anonymous>)
    at chrome-extension://hekejdakmnkficpkmibmiiadjcldfadl/js/options.js:95:27
```

Note: I tried both `unpacked-dev` and `unpacked-prod`. Same error.

**Comment by berrberr** [comment]
Thanks for the report! Fixed
